AWSTemplateFormatVersion: "2010-09-09"
Description: Creates a GuardDuty detector and enables/disables it.

Parameters:
  State:
    Type: String
    AllowedValues:
        - true
        - false
    Description: Choose "enable" or "disable" to apply either setting to the GuardDuty Selector.

Resources:
    GuardDutyDetector:
      Type: AWS::GuardDuty::Detector
      Properties: 
        Enable: !Ref State
        # An enum value that specifies how frequently updated findings are exported.
        FindingPublishingFrequency: "FIFTEEN_MINUTES"
    